website_controllers:
    resource:
        path: ../src/Controller/Website
        namespace: App\Controller\Website
    type: attribute
    name_prefix: 'website_'

admin_controllers:
    resource:
        path: ../src/Controller/Admin
        namespace: App\Controller\Admin
    type: attribute
    name_prefix: 'admin_'
    prefix: 'admin/'
